# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        carre: #nom du filtre
            quality: 75 #qualité de l'image
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                # name our first filter set "my_max_down_scale_filter"

        my_by_down_scale_filter:
            quality: 75
            filters:
                # use and setup the "downscale" filter
                downscale:
                    # input 1980x1280px -> output 792x512px
                    by: 0.25
